# -*- coding: utf-8 -*-
"""my_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_SJqVa7Lvh1tyWJnaOKv9wcw8CTT-v5
"""

# ===============================
# 1. 필요한 pip 설치
# ===============================
!pip install transformers==4.36.2
!pip install datasets
!pip install accelerate
!pip install sentencepiece
!pip install tqdm
!pip install numpy
!pip install pandas

# ===============================
# 2. IMDB 데이터 다운로드
# ===============================
!wget https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
!tar -xzf aclImdb_v1.tar.gz

import os
import random
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup
)
from tqdm import tqdm

# ==================================
# 0. 환경설정
# ==================================
seed = 1234
np.random.seed(seed)
random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# AMP 설정
scaler = torch.cuda.amp.GradScaler()

# ==================================
# 1. 데이터 로더 (텍스트만 저장)
# ==================================
def load_imdb_split(split_dir, sample_ratio=1.0):
    texts, labels = [], []
    for label in ["pos", "neg"]:
        folder = os.path.join(split_dir, label)
        files = os.listdir(folder)
        sample_count = int(len(files) * sample_ratio)

        sampled = random.sample(files, sample_count)
        for fname in sampled:
            with open(os.path.join(folder, fname), "r", encoding="utf-8") as f:
                texts.append(f.read())
            labels.append(1 if label == "pos" else 0)

    return pd.DataFrame({"text": texts, "label": labels})

# ==================================
# 2. 토크나이저
# ==================================
tokenizer = AutoTokenizer.from_pretrained("bert-large-cased")

class IMDBDataset(Dataset):
    def __init__(self, texts, labels, max_len=256):
        self.texts = texts
        self.labels = labels
        self.max_len = max_len

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, i):
        enc = tokenizer(
            self.texts[i],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[i])
        return item

# ==================================
# 3. FGM adversarial
# ==================================
class FGM:
    def __init__(self, model):
        self.model = model
        self.backup = {}

    def attack(self, epsilon=0.5, emb_name='embeddings'):
        for name, param in self.model.named_parameters():
            if param.requires_grad and emb_name in name:
                self.backup[name] = param.data.clone()
                if param.grad is None:
                    continue
                norm = torch.norm(param.grad)
                if norm != 0:
                    r_at = epsilon * param.grad / norm
                    param.data.add_(r_at)

    def restore(self, emb_name='embeddings'):
        for name, param in self.model.named_parameters():
            if name in self.backup:
                param.data = self.backup[name]
        self.backup = {}

# ==================================
# 4. 모델 생성
# ==================================
def create_model():
    return AutoModelForSequenceClassification.from_pretrained(
        "bert-large-cased",
        num_labels=2,
        hidden_dropout_prob=0.2,
        attention_probs_dropout_prob=0.2
    ).to(device)

# ==================================
# 5. 학습 함수 (AMP + FGM)
# ==================================
def train_model(model, train_loader, val_loader, save_path, epochs=2, lr=2e-5):
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.05)
    criterion = torch.nn.CrossEntropyLoss(label_smoothing=0.05)

    total_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(total_steps * 0.1),
        num_training_steps=total_steps
    )

    fgm = FGM(model)
    best_acc = 0.0

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for batch in tqdm(train_loader, desc=f"[Train {epoch+1}]"):
            batch = {k: v.to(device) for k, v in batch.items()}

            optimizer.zero_grad()

            with torch.cuda.amp.autocast():
                outputs = model(**batch)
                loss = criterion(outputs.logits, batch["labels"])

            scaler.scale(loss).backward()

            # FGM adversarial training
            fgm.attack()
            with torch.cuda.amp.autocast():
                adv_outputs = model(**batch)
                adv_loss = criterion(adv_outputs.logits, batch["labels"])
            scaler.scale(adv_loss).backward()
            fgm.restore()

            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            total_loss += loss.item()

        # Validation
        correct, total = 0, 0
        model.eval()
        with torch.no_grad():
            for batch in tqdm(val_loader, desc=f"[Val {epoch+1}]"):
                batch = {k: v.to(device) for k, v in batch.items()}
                with torch.cuda.amp.autocast():
                    logits = model(**batch).logits
                preds = logits.argmax(dim=1)

                correct += (preds == batch["labels"]).sum().item()
                total += len(preds)

        acc = correct / total
        print(f"Epoch {epoch+1} | Loss {total_loss:.4f} | Val Acc {acc:.4f}")

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), save_path)
            print("🔥 Best model saved")

    return best_acc

# ==================================
# 6. Test 평가
# ==================================
def evaluate_test(model, loader):
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for batch in tqdm(loader, desc="[Test]"):
            batch = {k: v.to(device) for k, v in batch.items()}
            with torch.cuda.amp.autocast():
                logits = model(**batch).logits
            preds = logits.argmax(dim=1)
            correct += (preds == batch["labels"]).sum().item()
            total += len(preds)

    acc = correct / total
    print(f"🎯 Test Accuracy: {acc:.4f}")
    return acc

# ==================================
# 7. 전체 파이프라인
# ==================================
def pipeline():

    # 1단계 소규모 학습
    small_train = load_imdb_split("aclImdb/train", sample_ratio=0.3)
    val_df = load_imdb_split("aclImdb/test", sample_ratio=0.2)

    train_loader = DataLoader(
        IMDBDataset(small_train["text"], small_train["label"]),
        batch_size=4, shuffle=True, num_workers=2, pin_memory=True
    )
    val_loader = DataLoader(
        IMDBDataset(val_df["text"], val_df["label"]),
        batch_size=4, shuffle=False, num_workers=2, pin_memory=True
    )

    model = create_model()
    print("\n🔥 Stage 1 Training")
    train_model(model, train_loader, val_loader, "warmup.pt")

    # 2단계 풀 데이터 학습
    full_train = load_imdb_split("aclImdb/train")
    full_loader = DataLoader(
        IMDBDataset(full_train["text"], full_train["label"]),
        batch_size=4, shuffle=True, num_workers=2, pin_memory=True
    )

    model = create_model()
    model.load_state_dict(torch.load("warmup.pt"))

    print("\n🔥 Stage 2 Training")
    train_model(model, full_loader, val_loader, "final.pt")

    # 테스트 평가
    test_df = load_imdb_split("aclImdb/test")
    test_loader = DataLoader(
        IMDBDataset(test_df["text"], test_df["label"]),
        batch_size=4, shuffle=False, num_workers=2, pin_memory=True
    )

    model.load_state_dict(torch.load("final.pt"))
    evaluate_test(model, test_loader)

pipeline()

import os
import torch
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm


device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

tokenizer = AutoTokenizer.from_pretrained("bert-large-cased")


# --------------------------------------
# Dataset
# --------------------------------------
class IMDBDataset(Dataset):
    def __init__(self, texts, labels, max_len=256):
        self.texts = texts
        self.labels = labels
        self.max_len = max_len

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, i):
        enc = tokenizer(
            self.texts[i],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[i])
        return item


# --------------------------------------
# Test 평가 함수
# --------------------------------------
def evaluate_test(model, loader):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for batch in tqdm(loader, desc="[Test]"):
            batch = {k: v.to(device) for k, v in batch.items()}
            logits = model(**batch).logits
            preds = logits.argmax(dim=1)
            correct += (preds == batch["labels"]).sum().item()
            total += len(preds)

    acc = correct / total
    print(f"🎯 Test Accuracy: {acc:.4f}")
    return acc


# --------------------------------------
# Test 데이터 로더
# --------------------------------------
def load_imdb_split(split_dir):
    texts, labels = [], []
    for label in ["pos", "neg"]:
        folder = os.path.join(split_dir, label)
        files = os.listdir(folder)

        for fname in files:
            with open(os.path.join(folder, fname), "r", encoding="utf-8") as f:
                texts.append(f.read())
            labels.append(1 if label == "pos" else 0)

    return texts, labels


# --------------------------------------
# 메인 실행부
# --------------------------------------
def run_test():

    print("📌 Loading IMDB Test Data (25,000 samples)...")

    texts, labels = load_imdb_split("aclImdb/test")
    test_dataset = IMDBDataset(texts, labels)
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

    print("📌 Loading model final.pt ...")
    model = AutoModelForSequenceClassification.from_pretrained(
        "bert-large-cased",
        num_labels=2
    ).to(device)

    model.load_state_dict(torch.load("final.pt", map_location=device))

    print("📌 Running evaluation ...")
    evaluate_test(model, test_loader)


# 실행
run_test()