# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jvYdKQKUywLAQpInO31j69gYdyXS0-Y
"""

import os
import sys
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import pandas as pd
from tqdm import tqdm


device = "cuda" if torch.cuda.is_available() else "cpu"


# -------------------------------
# Dataset
# -------------------------------
class TextDataset(Dataset):
    def __init__(self, texts, labels=None, max_len=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = AutoTokenizer.from_pretrained("bert-large-cased")
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, i):
        enc = self.tokenizer(
            self.texts[i],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        if self.labels is not None:
            item["labels"] = torch.tensor(self.labels[i])
        return item


# -------------------------------
# Load IMDB test data
# -------------------------------
def load_test_data(data_dir):
    texts, file_names = [], []

    for label in ["pos", "neg"]:
        folder = os.path.join(data_dir, label)
        if not os.path.exists(folder):
            continue

        files = sorted(os.listdir(folder))
        for fname in files:
            path = os.path.join(folder, fname)
            with open(path, "r", encoding="utf-8") as f:
                texts.append(f.read())
            file_names.append(fname)

    return texts, file_names


# -------------------------------
# Model factory
# -------------------------------
class LSTMClassifier(nn.Module):
    def __init__(self, hidden=128, num_classes=2):
        super().__init__()
        self.embedding = nn.Embedding(30522, 300)  # vocab size for BERT tokenizer
        self.lstm = nn.LSTM(300, hidden, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(hidden * 2, num_classes)

    def forward(self, input_ids, attention_mask=None):
        x = self.embedding(input_ids)
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        return self.fc(out)


def load_model(model_name):
    print("Loading my_model (BERT-based)...")
    model = AutoModelForSequenceClassification.from_pretrained(
        "bert-large-cased",
        num_labels=2
    ).to(device)

    model.load_state_dict(torch.load("my_model.pt", map_location=device))
    return model



# -------------------------------
# Inference
# -------------------------------
def run_inference(test_dir, model_name):
    print("📌 Loading test data...")
    texts, file_names = load_test_data(test_dir)

    dataset = TextDataset(texts)
    loader = DataLoader(dataset, batch_size=8, shuffle=False)

    print(f"📌 Loading model: {model_name}")
    model = load_model(model_name)
    model.eval()

    predictions = []

    print("📌 Running inference...")
    with torch.no_grad():
        for batch in tqdm(loader):
            batch = {k: v.to(device) for k, v in batch.items()}
            logits = model(**batch).logits
            pred = logits.argmax(dim=1).cpu().tolist()
            predictions.extend(pred)

    # Convert 0/1 to pos/neg
    pred_labels = ["pos" if p == 1 else "neg" for p in predictions]

    print("📌 Saving result.tsv ...")
    df = pd.DataFrame({
        "index": file_names,
        "prediction": pred_labels
    })

    df.to_csv("result.tsv", sep="\t", index=False)

    print("🎉 Done! Saved to result.tsv")


# -------------------------------
# main
# -------------------------------
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python test.py [data_dir] [model_name]")
        print("Example: python test.py ./aclImdb/test my_model")
        sys.exit(1)

    data_dir = sys.argv[1]
    model_name = sys.argv[2]

    run_inference(data_dir, model_name)